services:
  safevision:
    build: .
    container_name: safevision
    env_file: .env
    network_mode: host
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./unauthorized_faces:/opt/safevision/unauthorized_faces
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
